<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260611065643 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE bet (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, amount NUMERIC(10, 2) NOT NULL, odds_at_bet NUMERIC(5, 2) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, status VARCHAR(20) NOT NULL, user_id INT NOT NULL, sport_event_id INT NOT NULL, outcome_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_FBF0EC9BA76ED395 ON bet (user_id)');
        $this->addSql('CREATE INDEX IDX_FBF0EC9B47551731 ON bet (sport_event_id)');
        $this->addSql('CREATE INDEX IDX_FBF0EC9BE6EE6D63 ON bet (outcome_id)');
        $this->addSql('CREATE TABLE limit_config (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, deposit_daily NUMERIC(10, 2) DEFAULT NULL, deposit_weekly NUMERIC(10, 2) DEFAULT NULL, bet_daily NUMERIC(10, 2) DEFAULT NULL, bet_weekly NUMERIC(10, 2) DEFAULT NULL, pending_increase JSON DEFAULT NULL, user_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_31027F8FA76ED395 ON limit_config (user_id)');
        $this->addSql('CREATE TABLE outcome (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, label VARCHAR(255) NOT NULL, odds NUMERIC(5, 2) NOT NULL, is_winner BOOLEAN DEFAULT NULL, sport_event_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_30BC6DC247551731 ON outcome (sport_event_id)');
        $this->addSql('CREATE TABLE self_exclusion (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, start_date TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, end_date TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, user_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_62B75AE1A76ED395 ON self_exclusion (user_id)');
        $this->addSql('CREATE TABLE sport_event (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, sport VARCHAR(100) NOT NULL, participants JSON NOT NULL, event_date TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, status VARCHAR(20) NOT NULL, manager_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_8FD26BBE783E3463 ON sport_event (manager_id)');
        $this->addSql('CREATE TABLE transaction (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, amount NUMERIC(10, 2) NOT NULL, type VARCHAR(30) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, user_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_723705D1A76ED395 ON transaction (user_id)');
        $this->addSql('CREATE TABLE "user" (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, email VARCHAR(180) NOT NULL, roles JSON NOT NULL, password VARCHAR(255) NOT NULL, birthdate DATE NOT NULL, is_active BOOLEAN NOT NULL, wallet NUMERIC(10, 2) NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_8D93D649E7927C74 ON "user" (email)');
        $this->addSql('CREATE TABLE messenger_messages (id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, body TEXT NOT NULL, headers TEXT NOT NULL, queue_name VARCHAR(190) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, available_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, delivered_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_75EA56E0FB7336F0E3BD61CE16BA31DBBF396750 ON messenger_messages (queue_name, available_at, delivered_at, id)');
        $this->addSql('ALTER TABLE bet ADD CONSTRAINT FK_FBF0EC9BA76ED395 FOREIGN KEY (user_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE bet ADD CONSTRAINT FK_FBF0EC9B47551731 FOREIGN KEY (sport_event_id) REFERENCES sport_event (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE bet ADD CONSTRAINT FK_FBF0EC9BE6EE6D63 FOREIGN KEY (outcome_id) REFERENCES outcome (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE limit_config ADD CONSTRAINT FK_31027F8FA76ED395 FOREIGN KEY (user_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE outcome ADD CONSTRAINT FK_30BC6DC247551731 FOREIGN KEY (sport_event_id) REFERENCES sport_event (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE self_exclusion ADD CONSTRAINT FK_62B75AE1A76ED395 FOREIGN KEY (user_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE sport_event ADD CONSTRAINT FK_8FD26BBE783E3463 FOREIGN KEY (manager_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE transaction ADD CONSTRAINT FK_723705D1A76ED395 FOREIGN KEY (user_id) REFERENCES "user" (id) NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE bet DROP CONSTRAINT FK_FBF0EC9BA76ED395');
        $this->addSql('ALTER TABLE bet DROP CONSTRAINT FK_FBF0EC9B47551731');
        $this->addSql('ALTER TABLE bet DROP CONSTRAINT FK_FBF0EC9BE6EE6D63');
        $this->addSql('ALTER TABLE limit_config DROP CONSTRAINT FK_31027F8FA76ED395');
        $this->addSql('ALTER TABLE outcome DROP CONSTRAINT FK_30BC6DC247551731');
        $this->addSql('ALTER TABLE self_exclusion DROP CONSTRAINT FK_62B75AE1A76ED395');
        $this->addSql('ALTER TABLE sport_event DROP CONSTRAINT FK_8FD26BBE783E3463');
        $this->addSql('ALTER TABLE transaction DROP CONSTRAINT FK_723705D1A76ED395');
        $this->addSql('DROP TABLE bet');
        $this->addSql('DROP TABLE limit_config');
        $this->addSql('DROP TABLE outcome');
        $this->addSql('DROP TABLE self_exclusion');
        $this->addSql('DROP TABLE sport_event');
        $this->addSql('DROP TABLE transaction');
        $this->addSql('DROP TABLE "user"');
        $this->addSql('DROP TABLE messenger_messages');
    }
}
